"""Initial migration with all tables

Revision ID: 5acdd79a78be
Revises: 
Create Date: 2025-11-02 01:50:21.998111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acdd79a78be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_assignments_id'), table_name='dispatch_assignments')
    op.drop_table('dispatch_assignments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dispatches_id'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_serial_number'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_title'), table_name='dispatches')
    op.drop_table('dispatches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_title'), 'dispatches', ['title'], unique=False)
    op.create_index(op.f('ix_dispatches_serial_number'), 'dispatches', ['serial_number'], unique=1)
    op.create_index(op.f('ix_dispatches_id'), 'dispatches', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('dispatch_assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dispatch_id', sa.INTEGER(), nullable=False),
    sa.Column('assignee_id', sa.INTEGER(), nullable=False),
    sa.Column('action_required', sa.TEXT(), nullable=True),
    sa.Column('assigned_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_assignments_id'), 'dispatch_assignments', ['id'], unique=False)
    # ### end Alembic commands ###
